steps:
  # Build da imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'
      - '.'
    env:
      - 'CLOUDSDK_BUILD_TIMEOUT=1200'

  # Push para Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'

images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'

substitutions:
  _SERVICE_NAME: 'reddit-mlops'
  _PROJECT_ID: ''

options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY